from compreq.bounds import Bounds, get_bounds
from compreq.classifiers import get_python_classifiers, set_python_classifiers
from compreq.contexts import (
    Context,
    DefaultContext,
    DefaultPackageContext,
    PackageContext,
)
from compreq.io.poetry import PoetryPyprojectFile
from compreq.io.pyproject import PyprojectFile
from compreq.io.re import TextReFile
from compreq.io.text import TextRequirementsFile
from compreq.lazy import (
    EMPTY_REQUIREMENT,
    AllLazyReleaseSet,
    AnyMarker,
    AnyRelease,
    AnyReleaseSet,
    AnyRequirement,
    AnySpecifier,
    AnySpecifierOperator,
    AnySpecifierSet,
    AnyVersion,
    EagerLazyRelease,
    EagerLazyReleaseSet,
    EagerLazyVersion,
    LazyRelease,
    LazyReleaseSet,
    LazyRequirement,
    LazySpecifier,
    LazySpecifierSet,
    LazyVersion,
    PreLazyReleaseSet,
    ProdLazyReleaseSet,
    ReleaseLazyVersion,
    SpecifierLazyReleaseSet,
    SpecifierOperator,
    compose,
    get_lazy_release,
    get_lazy_release_set,
    get_lazy_requirement,
    get_lazy_specifier,
    get_lazy_specifier_set,
    get_lazy_version,
    get_marker,
    get_specifier_operator,
)
from compreq.levels import (
    MAJOR,
    MICRO,
    MINOR,
    REL_MAJOR,
    REL_MICRO,
    REL_MINOR,
    AnyLevel,
    IntLevel,
    Level,
    RelativeToFirstNonZeroLevel,
    get_level,
)
from compreq.operators import (
    CeilLazyVersion,
    CountLazyReleaseSet,
    FloorLazyVersion,
    MaxAgeLazyReleaseSet,
    MaximumLazyVersion,
    MaxLazyRelease,
    MinAgeLazyReleaseSet,
    MinimumLazyVersion,
    MinLazyRelease,
    ceil_ver,
    count,
    devreleases,
    extra,
    floor_ver,
    marker,
    max_age,
    max_ver,
    maximum_ver,
    min_age,
    min_ver,
    minimum_ver,
    package,
    pkg,
    prereleases,
    releases,
    specifier,
    specifier_set,
    url,
    v,
    version,
)
from compreq.paths import AnyPath
from compreq.pypireleases import get_pypi_releases
from compreq.pythonftp import ROOT as PYTHON_FTP_ROOT
from compreq.pythonftp import FtpDir, FtpFile, FtpPath, Url
from compreq.pythonreleases import get_python_releases
from compreq.releases import (
    Release,
    ReleaseSet,
    infer_and_set_successor,
    infer_successor,
)
from compreq.roots import CompReq
from compreq.time import UtcDatetime, is_utc_datetime, utc_now
from compreq.versiontokens import VersionToken

__version__ = "0.1.0"

__all__ = [
    "AllLazyReleaseSet",
    "AnyLevel",
    "AnyMarker",
    "AnyPath",
    "AnyRelease",
    "AnyReleaseSet",
    "AnyRequirement",
    "AnySpecifier",
    "AnySpecifierOperator",
    "AnySpecifierSet",
    "AnyVersion",
    "Bounds",
    "CeilLazyVersion",
    "CompReq",
    "Context",
    "CountLazyReleaseSet",
    "DefaultContext",
    "DefaultPackageContext",
    "EMPTY_REQUIREMENT",
    "EagerLazyRelease",
    "EagerLazyReleaseSet",
    "EagerLazyVersion",
    "FloorLazyVersion",
    "FtpDir",
    "FtpFile",
    "FtpPath",
    "IntLevel",
    "LazyRelease",
    "LazyReleaseSet",
    "LazyRequirement",
    "LazySpecifier",
    "LazySpecifierSet",
    "LazyVersion",
    "Level",
    "MAJOR",
    "MICRO",
    "MINOR",
    "MaxAgeLazyReleaseSet",
    "MaxLazyRelease",
    "MaximumLazyVersion",
    "MinAgeLazyReleaseSet",
    "MinLazyRelease",
    "MinimumLazyVersion",
    "PYTHON_FTP_ROOT",
    "PackageContext",
    "PoetryPyprojectFile",
    "PreLazyReleaseSet",
    "ProdLazyReleaseSet",
    "PyprojectFile",
    "REL_MAJOR",
    "REL_MICRO",
    "REL_MINOR",
    "RelativeToFirstNonZeroLevel",
    "Release",
    "ReleaseLazyVersion",
    "ReleaseSet",
    "SpecifierLazyReleaseSet",
    "SpecifierOperator",
    "TextReFile",
    "TextRequirementsFile",
    "Url",
    "UtcDatetime",
    "VersionToken",
    "__version__",
    "ceil_ver",
    "compose",
    "count",
    "devreleases",
    "extra",
    "floor_ver",
    "get_bounds",
    "get_lazy_release",
    "get_lazy_release_set",
    "get_lazy_requirement",
    "get_lazy_specifier",
    "get_lazy_specifier_set",
    "get_lazy_version",
    "get_level",
    "get_marker",
    "get_pypi_releases",
    "get_python_classifiers",
    "get_python_releases",
    "get_specifier_operator",
    "infer_and_set_successor",
    "infer_successor",
    "is_utc_datetime",
    "marker",
    "max_age",
    "max_ver",
    "maximum_ver",
    "min_age",
    "min_ver",
    "minimum_ver",
    "package",
    "pkg",
    "prereleases",
    "releases",
    "set_python_classifiers",
    "specifier",
    "specifier_set",
    "url",
    "utc_now",
    "v",
    "version",
]
